org.gradle.jvmargs=-Xmx768m -XX:MaxMetaspaceSize=384m -XX:+UseG1GC -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.daemon.idletimeout=30000
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.vfs.watch=false
org.gradle.console=plain
org.gradle.java.installations.auto-download=false
org.gradle.java.home=/usr/lib/jvm/temurin-25-jdk-amd64
mixin_version=0.8.5
mixin_booter_version=11.14
