package com.charles445.simpledifficulty.handler;

import com.charles445.simpledifficulty.api.SDCapabilities;
import com.charles445.simpledifficulty.api.config.JsonConfig;
import com.charles445.simpledifficulty.api.config.QuickConfig;
import com.charles445.simpledifficulty.api.config.json.JsonConsumableTemperature;
import com.charles445.simpledifficulty.api.temperature.TemporaryModifierGroupEnum;
import com.charles445.simpledifficulty.config.ModConfig;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.entity.living.LivingEntityUseItemEvent;
import net.minecraftforge.event.entity.living.LivingHurtEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

import java.util.List;

public class TemperatureHandler {
    @SubscribeEvent
    public void onLivingEntityUseItemFinish(LivingEntityUseItemEvent.Finish event) {
        if (!QuickConfig.isTemperatureEnabled()) {
            return;
        }
        
        if (event.getEntityLiving() instanceof EntityPlayer) {
            EntityPlayer player = (EntityPlayer) event.getEntityLiving();
            
            if (player.world.isRemote) {
                return;
            }
            
            ItemStack stack = event.getItem();
            ResourceLocation regName = stack.getItem().getRegistryName();
            
            // Prevent NPE crash if registry name is null (unregistered items)
            if (regName == null) {
                return;
            }
            
            List<JsonConsumableTemperature> consumableList = JsonConfig.consumableTemperature.get(regName.toString());
            
            if (consumableList != null) {
                for (JsonConsumableTemperature jct : consumableList) {
                    if (jct == null) {
                        continue;
                    }
                    
                    if (jct.matches(stack)) {
                        SDCapabilities.getTemperatureData(player).setTemporaryModifier(jct.group, jct.temperature, jct.duration);
                        break;
                    }
                }
            }
        }
    }

    /**
     * Captures custom damage parameters generated by Weather2 Remastered.
     * Applies rapid hypothermia changes if the user gets hit by dynamic hail blocks.
     */
    @SubscribeEvent
    public void onPlayerHurtByWeather(LivingHurtEvent event) {
        if (!QuickConfig.isTemperatureEnabled()) {
            return;
        }

        if (event.getEntityLiving() instanceof EntityPlayer) {
            EntityPlayer player = (EntityPlayer) event.getEntityLiving();

            if (player.world.isRemote) {
                return;
            }

            if ("hail".equals(event.getSource().getDamageType())) {
                SDCapabilities.getTemperatureData(player).setTemporaryModifier(
                    TemporaryModifierGroupEnum.DRINK.group(), 
                    ModConfig.server.temperature.wetValue, 
                    200
                );
            }
        }
    }
}
