modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/juraj-hrivnak/SimpleDifficulty/issues"

[[mods]]
modId="simpledifficulty"
version="0.8.0"
displayName="SimpleDifficulty"
updateJSONURL="https://raw.githubusercontent.com/juraj-hrivnak/SimpleDifficulty/master/modupdatechecker.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simpledifficulty-for-underdog"
logoFile="logo.png"
credits="Original concept and development by Charles445. Underdog fork and maintenance by juraj-hrivnak. Performance optimization, bug fixes, and port 1.16.5 by Onyx-i7."
authors="Charles445, juraj-hrivnak, Onyx-i7"
description='''
A survival mod that adds dynamic temperature and thirst mechanics to Minecraft 1.16.5, inspired by Tough As Nails. It features customizable hydration and environmental temperature effects.
'''